language: java

sudo: false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

env:
  matrix:
    - SUFFIX='-D jackson.version=2.5.0'
    - SUFFIX='-D jackson.version=2.5.5'
    - SUFFIX='-D jackson.version=2.6.7.1'
    - SUFFIX='-D jackson.version=2.7.9.3'
    - SUFFIX='-D jackson.version=2.8.11'
    - # as specified in pom.xml

script: ./mvnw clean verify $SUFFIX

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
